[project]
name = "litegen"
version = "0.1.0"
description = "A light-weight and high-efficient training framework for accelerating diffusion tasks."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "easydict==1.13",
    "einops==0.8.0",
    "importlib-metadata==7.1.0",
    "importlib-resources==6.4.0",
    "numpy==1.26.3",
    "pillow==10.2.0",
    "pyyaml==6.0.1",
    "transformers==4.41.1",
]
